# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Hotei' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Hotei
  pod ‘Charts’, ‘~> 3.0.1’

end

target 'HoteiW' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HoteiW

end

target 'HoteiW Extension' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HoteiW Extension

end
